puts "version $tcl_version"
puts "patchlevel [info patchlevel]"
puts "pkgPath is set to $tcl_pkgPath"
puts "autopath is set to $auto_path"
puts "Clock scan returns [clock scan 1752-09-02 -format %Y-%m-%d -locale en_US]"
puts "itcl version [package require itcl]"
puts "sqlite version [package require sqlite3]"
puts "tdbc version [package require tdbc]"
puts "tdbc::mysql version [package require tdbc::mysql]"
puts "tdbc::odbc version [package require tdbc::odbc]"
puts "tdbc::postgres version [package require tdbc::postgres]"
puts "Thread version [package require Thread]"
puts "tls version [package require tls]"
